sudo: required

language: python
python: 
    - '3.6'

services:
    - docker

env:
    - DOCKER_REPO=mpa-staging
    - DOCKER_ECR_URI=496397425809.dkr.ecr.us-west-2.amazonaws.com

before_install:
    - pip3 install awscli --upgrade
    - pip3 install fabric3

script: 
    - docker build -t mpa-staging --build-arg env=$DCMPA_ENVIRONMENT --build-arg name=$POSTGRES_DB_NAME --build-arg user=$POSTGRES_DB_USER  --build-arg passwd=$POSTGRES_USER_PASSWORD .
    - docker tag mpa-staging:latest 496397425809.dkr.ecr.us-west-2.amazonaws.com/mpa-staging:latest

after_success:
    - eval $(aws ecr get-login --region us-west-2 --no-include-email) 
    - docker push 496397425809.dkr.ecr.us-west-2.amazonaws.com/mpa-staging:latest
    - fab setup_docker setup_aws_creds
    - fab authenticate_docker pull_image run_container