sudo: required

language: python
python: 
    - '3.6'

services:
    - docker
  
env:
    - DOCKER_REPO=mpa
    - DOCKER_ECR_URI=496397425809.dkr.ecr.us-west-2.amazonaws.com
    - MATRIX=IDIOT

jobs:
    include:
        - stage: "Install"
          script: 
            - pip3 install awscli --upgrade
            # - pip3 install fabric3
        - stage: "Build"
          script:
            - docker build -t mpa --build-arg env=$DCMPA_ENVIRONMENT --build-arg name=$POSTGRES_DB_NAME --build-arg user=$POSTGRES_DB_USER  --build-arg passwd=$POSTGRES_USER_PASSWORD .
            - docker tag mpa:latest 496397425809.dkr.ecr.us-west-2.amazonaws.com/mpa:latest 
        - stage: "Deploy"
        if: commit_message =~ /deploy/
          script:
            - eval $(aws ecr get-login --region us-west-2 --no-include-email) 
            - docker push 496397425809.dkr.ecr.us-west-2.amazonaws.com/mpa:latest

            # TODO: Encrypt ssh-keys into the git and use them in travis.
            # - fab setup_docker setup_aws_creds
            # - fab authenticate_docker pull_image run_container