sudo: required

language: python
python: 
    - '3.6'

services:
    - docker


jobs:
    include:
        - stage: "Install"
          script: ".travis/install.sh"
        - stage: "Build"
          script: ".travis/build.sh" 
        - stage: "Deploy"
          script: ".travis/deploy.sh"
          if: commit_message =~ /deploy/

        # TODO: Encrypt ssh-keys into the git and use them in travis.
        # - fab setup_docker setup_aws_creds
        # - fab authenticate_docker pull_image run_container

