sudo: required

language: python

services:
    - docker

script: 
<<<<<<< HEAD
    - docker build -t mpa-staging --build-arg env=$DCMPA_ENVIRONMENT --build-arg name=$POSTGRES_DB_NAME --build-arg user=$POSTGRES_DB_USER  --build-arg passwd=$POSTGRES_USER_PASSWORD .
=======
    - docker build -t mpa-staging --build-arg env=$DCMPA_ENVIRONMENT --build-arg name=$POSTGRES_DB_NAME --build-arg user=$POSTGRES_DB_USER  --build-arg passwd=$POSTGRES_USER_PASSWORD --add-host="postgreslocalhost:ec2-54-243-216-33.compute-1.amazonaws.com" .
>>>>>>> master
    - docker tag mpa-staging:latest 496397425809.dkr.ecr.us-west-2.amazonaws.com/mpa-staging:latest

after_success:
    - eval $(aws ecr get-login --region us-west-2 --no-include-email) 
    - docker push 496397425809.dkr.ecr.us-west-2.amazonaws.com/mpa-staging:latest